FROM ghcr.io/archlinux/archlinux:latest
ARG username

RUN pacman-key --init && pacman-key --populate archlinux

RUN pacman -Syu --noconfirm \
    zsh \
    grml-zsh-config \
    vim \
    less

RUN pacman -Syu --noconfirm \
    nvidia-open \
    opencl-nvidia \
    cuda

RUN pacman -Syu --noconfirm \
    git \
    uv \
    gcc \
    make \
    cmake

RUN pacman -Syu --noconfirm \
    ripgrep

#RUN useradd --create-home --home-dir=/workdir --shell=/usr/bin/zsh $(. /etc/os-release && echo "$ID")
RUN useradd --create-home --home-dir=/workdir --shell=/usr/bin/zsh ${username}
USER 1000:1000
WORKDIR /workdir

#RUN git clone --depth=1 https://github.com/NVIDIA/cuda-samples.git /workdir/cuda-samples
#
#RUN mkdir /workdir/cuda-samples/cpp/1_Utilities/deviceQuery/build
#WORKDIR /workdir/cuda-samples/cpp/1_Utilities/deviceQuery/build
#RUN source /etc/profile ; cmake ..
#RUN make -j$(nproc)
#RUN ln -s /workdir/cuda-samples/cpp/1_Utilities/deviceQuery/build/deviceQuery /workdir/deviceQuery
#
#RUN mkdir /workdir/cuda-samples/cpp/1_Utilities/deviceQueryDrv/build
#WORKDIR /workdir/cuda-samples/cpp/1_Utilities/deviceQueryDrv/build
#RUN source /etc/profile ; cmake ..
#RUN make -j$(nproc)
#RUN ln -s /workdir/cuda-samples/cpp/1_Utilities/deviceQueryDrv/build/deviceQueryDrv /workdir/deviceQueryDrv
#
#RUN mkdir /workdir/cuda-samples/cpp/1_Utilities/topologyQuery/build
#WORKDIR /workdir/cuda-samples/cpp/1_Utilities/topologyQuery/build
#RUN source /etc/profile ; cmake ..
#RUN make -j$(nproc)
#RUN ln -s /workdir/cuda-samples/cpp/1_Utilities/topologyQuery/build/topologyQuery /workdir/topologyQuery
#
#WORKDIR /workdir

ENV UV_LINK_MODE=copy
